# Generated by Django 3.0.3 on 2021-06-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Title', '0005_id_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='unique_id',
            field=models.CharField(max_length=11),
        ),
    ]
