# Generated by Django 3.0.7 on 2022-05-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Title', '0007_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='id',
            options={'verbose_name': 'Unique ID', 'verbose_name_plural': 'Unique IDs'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Log Index', 'verbose_name_plural': 'Log Index'},
        ),
    ]
