# Generated by Django 3.0.7 on 2022-05-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Title', '0008_auto_20220504_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='log',
            name='doi',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Issue'),
        ),
        migrations.AlterField(
            model_name='log',
            name='dor',
            field=models.DateField(verbose_name='Date of Return'),
        ),
        migrations.AlterField(
            model_name='log',
            name='edor',
            field=models.DateField(verbose_name='Expected Date of Return'),
        ),
        migrations.AlterField(
            model_name='log',
            name='registration_no',
            field=models.IntegerField(default=0),
        ),
    ]
