# Generated by Django 3.0.7 on 2022-05-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Title', '0009_auto_20220504_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='dor',
            field=models.DateField(blank=True, verbose_name='Date of Return'),
        ),
    ]
