# Generated by Django 3.0.7 on 2022-05-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Title', '0012_auto_20220504_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='student_id',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
