# Generated by Django 3.1.4 on 2022-05-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Title', '0013_auto_20220505_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='unique_id',
        ),
    ]
